### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#10]
Use of commands should be configurable. A command should be usable by everyone, noone, or specific users (identified by username+hostmask)

**Comment by SparkyRailgun** [comment]
This should also be extended to channels for each plugin, so functionality can be disabled on certain channels (for example, html ptitle parsing in a channel where a bot already does that)

**Comment by wrycu** [comment]
Permissioning for users was handled in c211b4ac747e65e3d5bee1b161be22c7a39f8471.
