### ISSUE TITLE
Send raw IRC commands

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#12]
Not necessary for normal use, being able to send raw commands is nontheless handy for fring cases. I currently use it on voss to identify the bot to nickserv (actually i don't bother since it's hosted on my vps, but...)

> !sendraw "PRIVMSG NickServ : identify Toss password"

**Comment by wrycu** [comment]
I'm currently working on this but whatever I do, the twisted component doesn't appear to pass the raw command along.

**Comment by wrycu** [comment]
>(11:26:31 PM) CarlThansk: .sendraw PRIVMSG carlthansk : identify Toss password
(11:26:31 PM) toss_test: Command executed

Results in
>(11:26:31 PM) toss_test:  identify Toss password

**Comment by SparkyRailgun** [comment]
👌
