### ISSUE TITLE
Twitch title support

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#25]
toss returns simply 'Twitch' when a stream is linked. I think Twitch updates the title with a script during load.

Ideally it would report the name of the stream, not just the html title, but anything is better than nothing.

**Comment by wrycu** [comment]
(9:35:57 PM) CarlThansk: http://www.twitch.tv/wrycu

(9:35:58 PM) toss_test: Desktop | Powered by GeForce GTX
