### ISSUE TITLE
implement basic responses to highlights

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#3]
Bot should respond to messages directed at it in turn, but not be able to actually conversate (because it's a dumb bot)

>Sparky: Toss: how are you?
>Toss: I'm fine thanks, Sparky!

>Sparky: trains are the best, isn't that right Toss?
>Sparky: Yep!

It should choose from an array of responses, ideally exposed to the config.

**Comment by wrycu** [comment]
Closing as a duplicate of #16.
