### ISSUE TITLE
tell function

### ISSUE THREAD

**Issue by SparkyRailgun** [wrycu/toss#4]
Send a message to a user the next time they speak in the channel

>Sparky: !tell Wrycu i like trains
>Toss: Okay Sparky! I will tell them next time i see them.
>...
>Wrycu: wow i'm so good at bus simulator
>Toss: Wrycu, Sparky wanted me to tell you this! 'i like trains'

Should be sent to the channel by default (for promoting community interaction). Perhaps if the command is sent in a query, the tell should go in a query too. The bot would need to react to that user in multiple channels on the server, though.

In the event of multiple-server compatibility, tell should work on a per-server basis.

**Comment by wrycu** [comment]
>(10:40:58 PM) CarlThansk: .tell thansk_carl you're dumb
>(10:40:59 PM) toss_test: Ok, I will tell them that the next time I see them.
>(10:41:04 PM) CarlThansk: that'll show him
>(10:41:15 PM) thansk_carl: omg hi guys
>(10:41:15 PM) toss_test: CarlThansk would like me to tell you the following: you're dumb
